# Generated by Django 4.2.1 on 2023-05-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventry_app', '0003_alter_category_createdon_alter_category_modifiedon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='createdOn',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='modifiedOn',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='image1',
            name='createdOn',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='image1',
            name='modifiedOn',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='product1',
            name='createdOn',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='product1',
            name='modifiedOn',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
